import { create } from "zustand";
import { Course } from "@/types/course";

interface CoursesStore {
    popularCourses: Course[];
    isLoading: boolean;
    error: string | null;
    setPopularCourses: (courses: Course[]) => void;
    setLoading: (loading: boolean) => void;
    setError: (error: string | null) => void;
}

// Определим доступные направления
export const DIRECTIONS = [
    "Все направления",
    "Дизайн",
    "Маркетинг",
    "Управление",
    "Аналитика",
    "Программирование",
] as const;

export type Direction = (typeof DIRECTIONS)[number];

// Обновляем моковые данные с добавлением direction
export const MOCK_COURSES: Course[] = [
    {
        id: "1",
        title: "JavaScript Основы",
        author: {
            name: "Иван Петров",
            role: "Senior JavaScript Developer",
            avatar: "/avatars/ivan_petrov.png",
        },
        level: "beginner",
        direction: "Frontend",
        duration: "32h",
        description:
            "Изучите основы JavaScript с нуля. Курс для начинающих разработчиков.",
        price: {
            current: 5900,
            old: 7900,
        },
        tags: ["JavaScript", "Frontend", "Web"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        image: "/course-images/javascript-basics.jpg",
        isFree: false,
        hasEmployment: true,
        rating: 4.8,
        studentsCount: 1250,
        completionRate: 85,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "2",
        title: "Python для Data Science",
        author: {
            name: "Мария Петрова",
            role: "Data Scientist",
            avatar: "/avatars/maria_petrova.png",
        },
        level: "intermediate",
        direction: "Аналитика",
        duration: "48h",
        description:
            "Изучите Python для анализа данных, машинного обучения и визуализации.",
        price: {
            current: 4900,
        },
        tags: ["Python", "Data Science", "ML"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1518818608552-195ed130cdf4?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.2,
        studentsCount: 80,
        completionRate: 75,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "3",
        title: "Основы JavaScript",
        author: {
            name: "Дмитрий Сидоров",
            role: "Frontend Developer",
            avatar: "/avatars/dmitry_sidorov.png",
        },
        level: "beginner",
        direction: "Программирование",
        duration: "24h",
        description:
            "Изучите основы JavaScript с нуля и создайте свои первые веб-приложения.",
        price: {
            current: 0,
        },
        tags: ["JavaScript", "Web", "Frontend"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        isFree: true,
        image: "https://images.unsplash.com/photo-1613490900233-141c5560d75d?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.0,
        studentsCount: 50,
        completionRate: 60,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "4",
        title: "React Advanced",
        author: {
            name: "Игорь Смирнов",
            role: "Senior Developer",
            avatar: "/avatars/igor_smirnov.png",
        },
        level: "advanced",
        direction: "Программирование",
        duration: "40h",
        description:
            "Продвинутый курс по React, Redux, TypeScript и оптимизации производительности.",
        price: {
            current: 7900,
            old: 9900,
        },
        tags: ["React", "Redux", "TypeScript"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.8,
        studentsCount: 150,
        completionRate: 90,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "5",
        title: "Adobe Photoshop Mastery",
        author: {
            name: "Анна Королева",
            role: "Графический дизайнер",
            avatar: "/avatars/anna_koroleva.png",
        },
        level: "intermediate",
        direction: "Дизайн",
        duration: "28h",
        description:
            "Освойте профессиональные техники работы в Photoshop для создания впечатляющих изображений.",
        price: {
            current: 4900,
        },
        tags: ["Design", "Photoshop"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1609619385002-f40f1df9b7eb?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.3,
        studentsCount: 100,
        completionRate: 80,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "6",
        title: "iOS Development with Swift",
        author: {
            name: "Павел Волков",
            role: "iOS Developer",
            avatar: "/avatars/pavel_volkov.png",
        },
        level: "intermediate",
        direction: "Мобильная разработка",
        duration: "56h",
        description:
            "Создавайте приложения для iOS с использованием Swift и SwiftUI.",
        price: {
            current: 8900,
        },
        tags: ["iOS", "Swift", "Mobile"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1650636353551-1275516077b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.7,
        studentsCount: 180,
        completionRate: 95,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "7",
        title: "DevOps Essential",
        author: {
            name: "Артем Соколов",
            role: "DevOps Engineer",
            avatar: "/avatars/artem_sokolov.png",
        },
        level: "intermediate",
        direction: "DevOps",
        duration: "44h",
        description:
            "Изучите основные инструменты и практики DevOps: Docker, Kubernetes, CI/CD.",
        price: {
            current: 6900,
            old: 8900,
        },
        tags: ["DevOps", "Docker", "Kubernetes"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1668854096791-df5455fb60ee?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.6,
        studentsCount: 120,
        completionRate: 80,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "8",
        title: "Node.js Backend Разработка",
        author: {
            name: "Максим Чернов",
            role: "Backend Developer",
            avatar: "/avatars/maxim_chernov.png",
        },
        level: "intermediate",
        direction: "Backend",
        duration: "52h",
        description:
            "Создавайте масштабируемые веб-приложения с использованием Node.js, Express и MongoDB.",
        price: {
            current: 6900,
            old: 8900,
        },
        tags: ["Node.js", "Express", "Backend"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.4,
        studentsCount: 100,
        completionRate: 75,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "9",
        title: "Django для веб-разработки",
        author: {
            name: "Елена Васильева",
            role: "Backend Developer",
            avatar: "/avatars/elena_vasileva.png",
        },
        level: "intermediate",
        direction: "Backend",
        duration: "48h",
        description:
            "Разработка веб-приложений на Python с использованием Django framework.",
        price: {
            current: 5900,
        },
        tags: ["Python", "Django", "Backend"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.3,
        studentsCount: 80,
        completionRate: 70,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "10",
        title: "Flutter Mobile Development",
        author: {
            name: "Андрей Козлов",
            role: "Mobile Developer",
            avatar: "/avatars/andrey_kozlov.png",
        },
        level: "intermediate",
        direction: "Мобильная разработка",
        duration: "60h",
        description:
            "Создавайте кроссплатформенные мобильные приложения с Flutter и Dart.",
        price: {
            current: 7900,
        },
        tags: ["Flutter", "Dart", "Mobile"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg",
        isFree: false,
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        hasEmployment: true,
        rating: 4.5,
        studentsCount: 150,
        completionRate: 85,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "11",
        title: "PostgreSQL Мастер-класс",
        author: {
            name: "Ольга Новикова",
            role: "Database Administrator",
            avatar: "/avatars/olga_novikova.png",
        },
        level: "advanced",
        direction: "Базы данных",
        duration: "36h",
        description:
            "Глубокое погружение в PostgreSQL: оптимизация, масштабирование и администрирование.",
        price: {
            current: 5900,
        },
        tags: ["PostgreSQL", "Databases", "SQL"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.2,
        studentsCount: 60,
        completionRate: 70,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "12",
        title: "Автоматизация тестирования",
        author: {
            name: "Сергей Белов",
            role: "QA Engineer",
            avatar: "/avatars/sergey_belov.png",
        },
        level: "intermediate",
        direction: "QA",
        duration: "44h",
        description:
            "Изучите автоматизированное тестирование с Selenium, TestNG и Jenkins.",
        price: {
            current: 4900,
        },
        tags: ["QA", "Selenium", "Testing"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.0,
        studentsCount: 50,
        completionRate: 60,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "13",
        title: "Кибербезопасность: Основы",
        author: {
            name: "Николай Морозов",
            role: "Cybersecurity Expert",
            avatar: "/avatars/nikolai_morozov.png",
        },
        level: "beginner",
        direction: "Кибербезопасность",
        duration: "50h",
        description:
            "Изучите основы информационной безопасности и этичного хакинга.",
        price: {
            current: 6900,
        },
        tags: ["Security", "Ethical Hacking", "Network"],
        logo: "",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.3,
        studentsCount: 70,
        completionRate: 70,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "14",
        title: "3D моделирование в Blender",
        author: {
            name: "Марина Светлова",
            role: "3D Artist",
            avatar: "/avatars/marina_svetlova.png",
        },
        level: "beginner",
        direction: "3D Modeling",
        duration: "56h",
        description: "Создавайте 3D модели и анимации с нуля в Blender.",
        price: {
            current: 5900,
        },
        tags: ["3D", "Blender", "Animation"],
        logo: "",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.1,
        studentsCount: 50,
        completionRate: 60,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "15",
        title: "Unreal Engine Game Development",
        author: {
            name: "Виктор Громов",
            role: "Game Developer",
            avatar: "/avatars/viktor_gromov.png",
        },
        level: "intermediate",
        direction: "Game Dev",
        duration: "70h",
        description:
            "Разработка игр на Unreal Engine 5 с использованием Blueprint и C++.",
        price: {
            current: 8900,
        },
        tags: ["Game Dev", "Unreal Engine", "C++"],
        logo: "",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.7,
        studentsCount: 180,
        completionRate: 90,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "16",
        title: "Machine Learning Basics",
        author: {
            name: "Александр Кузнецов",
            role: "Data Scientist",
            avatar: "/avatars/alexander_kuznetsov.png",
        },
        level: "beginner",
        direction: "Аналитика",
        duration: "40h",
        description:
            "Изучите основы машинного обучения и его применение в реальных задачах.",
        price: {
            current: 4500,
        },
        tags: ["Machine Learning", "Data Science"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/machinelearning/machinelearning-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.0,
        studentsCount: 40,
        completionRate: 50,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "17",
        title: "Advanced CSS Techniques",
        author: {
            name: "Екатерина Смирнова",
            role: "Frontend Developer",
            avatar: "/avatars/ekaterina_smirnova.png",
        },
        level: "advanced",
        direction: "Frontend",
        duration: "30h",
        description:
            "Углубитесь в продвинутые техники CSS для создания сложных интерфейсов.",
        price: {
            current: 5000,
        },
        tags: ["CSS", "Frontend"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.5,
        studentsCount: 80,
        completionRate: 70,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "18",
        title: "Introduction to Cloud Computing",
        author: {
            name: "Сергей Петров",
            role: "Cloud Engineer",
            avatar: "/avatars/sergey_petrov.png",
        },
        level: "intermediate",
        direction: "DevOps",
        duration: "50h",
        description:
            "Изучите основы облачных технологий и их применение в бизнесе.",
        price: {
            current: 6000,
        },
        tags: ["Cloud", "DevOps"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cloud/cloud-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.3,
        studentsCount: 100,
        completionRate: 75,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "19",
        title: "Game Development with Unity",
        author: {
            name: "Андрей Сидоров",
            role: "Game Developer",
            avatar: "/avatars/andrey_sidorov.png",
        },
        level: "intermediate",
        direction: "Game Dev",
        duration: "65h",
        description: "Создавайте игры с использованием Unity и C#.",
        price: {
            current: 7500,
        },
        tags: ["Unity", "Game Dev"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.6,
        studentsCount: 150,
        completionRate: 85,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "20",
        title: "Digital Marketing Strategies",
        author: {
            name: "Мария Коваленко",
            role: "Digital Marketer",
            avatar: "/avatars/maria_kovalenko.png",
        },
        level: "intermediate",
        direction: "Маркетинг",
        duration: "45h",
        description: "Изучите стратегии цифрового маркетинга и их применение.",
        price: {
            current: 4000,
        },
        tags: ["Marketing", "Digital"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/marketing/marketing-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.1,
        studentsCount: 50,
        completionRate: 50,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "21",
        title: "Blockchain Fundamentals",
        author: {
            name: "Иван Громов",
            role: "Blockchain Developer",
            avatar: "/avatars/ivan_gromov.png",
        },
        level: "beginner",
        direction: "Blockchain",
        duration: "50h",
        description:
            "Изучите основы блокчейна и его применение в различных отраслях.",
        price: {
            current: 5500,
        },
        tags: ["Blockchain"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/blockchain/blockchain-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.2,
        studentsCount: 60,
        completionRate: 60,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "22",
        title: "Cybersecurity Essentials",
        author: {
            name: "Ольга Васильева",
            role: "Cybersecurity Specialist",
            avatar: "/avatars/olga_vasileva.png",
        },
        level: "intermediate",
        direction: "Кибербезопасность",
        duration: "60h",
        description: "Изучите основы кибербезопасности и защиты информации.",
        price: {
            current: 7000,
        },
        tags: ["Cybersecurity"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/security/security-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.4,
        studentsCount: 100,
        completionRate: 75,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "23",
        title: "Data Analysis with Python",
        author: {
            name: "Алексей Федоров",
            role: "Data Analyst",
            avatar: "/avatars/alexey_fedorov.png",
        },
        level: "intermediate",
        direction: "Аналитика",
        duration: "50h",
        description:
            "Изучите анализ данных с использованием Python и библиотек.",
        price: {
            current: 4800,
        },
        tags: ["Python", "Data Analysis"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.0,
        studentsCount: 50,
        completionRate: 50,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "24",
        title: "Introduction to Artificial Intelligence",
        author: {
            name: "Светлана Петрова",
            role: "AI Researcher",
            avatar: "/avatars/svetlana_petrova.png",
        },
        level: "beginner",
        direction: "AI",
        duration: "40h",
        description:
            "Изучите основы искусственного интеллекта и его применение.",
        price: {
            current: 5000,
        },
        tags: ["AI", "Artificial Intelligence"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/artificialintelligence/artificialintelligence-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.1,
        studentsCount: 40,
        completionRate: 50,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "25",
        title: "Web Development Bootcamp",
        author: {
            name: "Дмитрий Кузнецов",
            role: "Web Developer",
            avatar: "/avatars/dmitry_kuznetsov.png",
        },
        level: "intermediate",
        direction: "Web Development",
        duration: "70h",
        description:
            "Полный курс по веб-разработке: от основ до продвинутых технологий.",
        price: {
            current: 8000,
        },
        tags: ["Web Development"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/web/web-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.6,
        studentsCount: 150,
        completionRate: 85,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "26",
        title: "Mobile App Development with React Native",
        author: {
            name: "Анастасия Смирнова",
            role: "Mobile Developer",
            avatar: "/avatars/anastasia_smirnova.png",
        },
        level: "intermediate",
        direction: "Мобильная разработка",
        duration: "60h",
        description:
            "Создавайте мобильные приложения с использованием React Native.",
        price: {
            current: 7500,
        },
        tags: ["React Native", "Mobile"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.4,
        studentsCount: 120,
        completionRate: 80,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "27",
        title: "SEO Optimization Techniques",
        author: {
            name: "Игорь Сидоров",
            role: "SEO Specialist",
            avatar: "/avatars/igor_sidorov.png",
        },
        level: "intermediate",
        direction: "Маркетинг",
        duration: "40h",
        description:
            "Изучите техники SEO оптимизации для повышения видимости сайтов.",
        price: {
            current: 4000,
        },
        tags: ["SEO", "Marketing"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/seo/seo-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.2,
        studentsCount: 50,
        completionRate: 60,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "28",
        title: "Introduction to Virtual Reality",
        author: {
            name: "Александр Громов",
            role: "VR Developer",
            avatar: "/avatars/alexander_gromov.png",
        },
        level: "beginner",
        direction: "VR",
        duration: "50h",
        description: "Изучите основы виртуальной реальности и ее применение.",
        price: {
            current: 6000,
        },
        tags: ["VR", "Virtual Reality"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vr/vr-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.3,
        studentsCount: 70,
        completionRate: 70,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "29",
        title: "Ethical Hacking Basics",
        author: {
            name: "Николай Морозов",
            role: "Cybersecurity Expert",
            avatar: "/avatars/nikolai_morozov.png",
        },
        level: "intermediate",
        direction: "Кибербезопасность",
        duration: "50h",
        description: "Изучите основы этичного хакинга и защиты систем.",
        price: {
            current: 7000,
        },
        tags: ["Ethical Hacking", "Cybersecurity"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hacking/hacking-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.4,
        studentsCount: 80,
        completionRate: 75,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
    {
        id: "30",
        title: "Data Visualization with Tableau",
        author: {
            name: "Елена Васильева",
            role: "Data Analyst",
            avatar: "/avatars/elena_vasileva.png",
        },
        level: "intermediate",
        direction: "Аналитика",
        duration: "40h",
        description: "Изучите визуализацию данных с использованием Tableau.",
        price: {
            current: 4800,
        },
        tags: ["Data Visualization", "Tableau"],
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tableau/tableau-original.svg",
        isFree: false,
        image: "/course-school-bg.svg",
        hasEmployment: true,
        rating: 4.0,
        studentsCount: 40,
        completionRate: 50,
        isPopular: true,
        updatedAt: "",
        language: "",
    },
] as const;

// Определите типы для уровней сложности
export type CourseLevel = "Начинающий" | "Средний" | "Продвинутый";

// Обновите LEVEL_MAPPING
export const LEVEL_MAPPING: Record<CourseLevel, string> = {
    Начинающий: "beginner",
    Средний: "intermediate",
    Продвинутый: "advanced",
} as const;

// Обратный маппинг для отображения
export const LEVEL_DISPLAY = {
    beginner: "Начинающий",
    intermediate: "Средний",
    advanced: "Продвинутый",
} as const;

export const useCoursesStore = create<CoursesStore>((set) => ({
    popularCourses: MOCK_COURSES, // Инициализируем store моковыми данными
    isLoading: false,
    error: null,
    setPopularCourses: (courses) => set({ popularCourses: courses }),
    setLoading: (loading) => set({ isLoading: loading }),
    setError: (error) => set({ error }),
}));
